In [1]:
import numpy as np

In [3]:
#creat array
a = np.array([1,2,3,4,5])

print(a)

#Print 1 element
print(a[1])

[1 2 3 4 5]
2


In [8]:
#Create 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix: ", matrix)
print("Cot 2 phan tu 2: ",matrix[2,2])

Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Cot 2 phan tu 2:  9


In [11]:
#How to create array!
#create array full 0
a = np.zeros(6)
print(a)

#creat array full 1
a = np.ones(3)
print(a)

#create empty array (to call nearest number)
a = np.ones(6)
print(a)

#create range(0,99)
a = np.arange(100)
print(a)

#create elements with equal spacing
a = np.linspace(0,10,num=5)
print(a)

#identify data types
a = np.ones(5, dtype=np.int64)
print(a)


[0. 0. 0. 0. 0. 0.]
[1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]
[1 1 1 1 1]


In [14]:
#Add, del, sort array
#init array
arr = np.array([1, 2, 3, 7, 6, 5])
print(arr)
#sort 
arr = np.sort(arr)
print(arr)
#!sort
arr = np.sort(arr)[::-1]
print(arr)
arr = np.append(arr, 10)
print(arr)
#del a position in the array
arr = np.delete(arr, 2)
print(arr)


[1 2 3 7 6 5]
[1 2 3 5 6 7]
[7 6 5 3 2 1]
[ 7  6  5  3  2  1 10]
[ 7  6  3  2  1 10]


In [19]:
#create 2d array
arr = np.array([[1, 2, 3],
                [6, 5, 4],
                [9, 7, 8]])
sort_by_row = -np.sort(-arr, axis =1) #giam dan
print(sort_by_row)
sort_by_col = -np.sort(-arr, axis =0) #giam dan
print(sort_by_col)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 7 8]
 [6 5 4]
 [1 2 3]]


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

#Su dung thuoc tinh de lay thong tin ve mang
so_chieu = arr.ndim #2chieu
kich_thuoc = arr.size 
hinh_dang = arr.shape #so hang x so cot (2x3) => (2,3)
print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)


Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [21]:
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float) # Ep sang kieu  float
print(arr_float)

[1. 2. 3. 4. 5.]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 8 ,7])
reshaped_arr = arr.reshape(2,4) #Chuyen hang thanh 2 ,cot thanh 4
print(reshaped_arr)
reshaped_arr = arr.reshape(4,2)#Chuyen cot thanh 2 ,hang thanh  4
print(reshaped_arr)

[[1 2 3 4]
 [5 6 8 7]]
[[1 2]
 [3 4]
 [5 6]
 [8 7]]


In [23]:
reshaped_arr = reshaped_arr.flatten() #flatten chuyen thanh mang 1 chieu
print(reshaped_arr)

[1 2 3 4 5 6 8 7]


In [24]:
#cat lat
arr = np.array([1, 2, 3, 4, 5, 6 ,7 , 8, 9])

sub_arr = arr[3:6] #cat het chi lay trong khoang 3-6(4-7)
print(sub_arr)

sub_arr= arr[:-3] #dem nguoc tu 1(0) ve 9(-1)...
print(sub_arr)  #':' truoc la se lay cac phan tu truoc [-3]

sub_arr= arr[-3:] #dem nguoc tu 1(0) ve 9(-1)... se lay cac phan tu sau -3(7) ->789
#print(sub_arr) # ':' dang sau la lay cac phan tu sau [-3]

[4 5 6]
[1 2 3 4 5 6]
[7 8 9]


In [25]:
#chuyen vi mang bang transpose
arr = np.array([[1,2,3,4], [8,7,6,5]])
print(arr)
transposed =arr.T #transpose bang cach .T va numpy.transpose()
print(transposed)

[[1 2 3 4]
 [8 7 6 5]]
[[1 8]
 [2 7]
 [3 6]
 [4 5]]


In [29]:
#noi mang bang ham np.concatenate
a = np.array([1,2,3,4])
b = np.array([8,7,6,5])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 8 7 6 5]


In [32]:
arr = np.array([1,2,3,4])
#tinh tong cac phan tu trong mang bang sum
arr_sum = np.sum(arr)
print("Tong cac phan tu trong mang", arr_sum)
#tinh trung binh cong cac phan tu trong mang bang mean
arr_mean = np.mean(arr)
print("trung binh cong cac phan tu trong mang", arr_mean)
#tinh min max bang min max
arr_min = np.min(arr)
print("Min: ",arr_min)
arr_max = np.max(arr)
print("Max: ",arr_max)
#tinh do lech chuan bang ham std (do luong do phan tan of data)
arr_std = np.std(arr)
print("do lech chuan: ",arr_std)
#tinh tong tich chap cua hai mang bang ham dot
a = np.array([1,2,3,4])
b = np.array([8,7,6,5])
arr_dot = np.dot(a, b)
print("tong tich chap cua hai mang: ",arr_dot)
#tinh phuong sai cua mang bang ham var (do luong do bien thien of data)
arr_var = np.var(arr)
print("Phuong sai cua mang:", arr_var)

Tong cac phan tu trong mang 10
trung binh cong cac phan tu trong mang 2.5
Min:  1
Max:  4
do lech chuan:  1.118033988749895
tong tich chap cua hai mang:  60
Phuong sai cua mang: 1.25
